config/routes.rb
Weblog::Application.routes.draw do

  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, 
            controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

 get "/jspractices" => "jspractice#index"
 get "/exercise1" => "jspractice#exercise1"

  get "/about_us" => "home#about"

  get "/welcome" => "home#welcome"

  get "/faq" => "home#faq"

  get "/help" => "help#index"

    resources :answers, only: [] do
      resources :comments, only: [:create, :destroy]
    end

  resources :questions  do#, except: #OR# only: [:index, :new, :create]
    resources :favourites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
    
    resources :answers
     
     member do
        post :vote_up
        post :vote_down
      end
      
      post :search, on: :collection

    end

  root "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base

  has_attached_file :image,
                    #need Imagemagick gem first: styles: { medium: "300x300>", thumb: "100x100"},
                    default_url: ActionController::Base.helpers.asset_path("missing")

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  #mount_uploader :image, ImageUploader

  validates :title, presence: true, uniqueness: true

  validates_presence_of :description, message: "must be present"

  after_initialize :set_defaults


  default_scope {order ("title ASC") }

  #questions belong to an individual user
  belongs_to :user

  has_many :votes, dependent: :destroy
  has_many :voted_users, through: :votes, source: :user

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  has_many :favourites, dependent: :destroy
  has_many :favourited_users, through: :favourites, source: :user

  has_one :question_detail
  # Methods for manipulating question_detail DB:
  # ~> question.build_question_detail(notes: "hello")
  # ~> question.create_question_detail(notes: "hello")

  has_many :answers, dependent: :destroy
  # question.answers(notes: "hello")



  has_many :comments, through: :answers
  #makes Answer DB schema dependent on Question schema


###########SAME THING BELOW: scope and self.recent_ten #############
  # scope :recent_ten, -> { order("created_at DESC").limit(10) }
  # ## -> sign is same as lambda

# OR


  def self.recent_ten
    order("created_at DESC").limit(10)
  end
##########

#Difference between method 1 and 2:  "x" is a variable you can define the number of DB entries to print

###########SAME THING BELOW:  scope and self.recent(x)

scope :recent, lambda {|x| order("created_at DESC").limit(x) }



# OR

  # def self.recent(x)
  #     order("created_at DESC").limit(x)
  # end
###########################

scope :after, lambda {|date| where(["created_at DESC"]).limit(x) }
##DEBUG NOTE: Above added as Copy from Tam's app

before_save :capitalize_title

  private
  
  #makes title inputs capitalized in database
  def capitalize_title
    self.title.capitalize!
  end
  
  def set_defaults 
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]

##This needs to be called to apply private method find_question on specified pages:
before_action :find_question, only: [:edit, :update, :destroy]


def index
  @recent_questions = Question.recent(3)
  @questions = Question.limit(10)
end

def new
  @question = Question.new
end

def create
  @question = Question.new(question_params)
    #^Replaces below due to private method question_params
    #@question = Question.new(params.require(:question).permit(:title, :description))
  
  @question.user = current_user 
  if @question.save
  redirect_to questions_path, notice: "Question created successfully!"
  else
    render :new
  end
end

def show
  @question = Question.find(params[:id])
  @answer = Answer.new
  @answers = @question.answers.ordered_by_creation
  if user_signed_in?
    @favourite = current_user.favourite_for(@question)
    @vote = current_user.vote_for(@question) || Vote.new
  end

end

def edit
  #CanCan/ActiveAdmin used here: 
  redirect_to root_path, alert: "Access Denied" unless can? :edit, @question

end

def update
  if @question.update_attributes(question_params)
    expire_fragment "recent_questions"
    redirect_to @question, notice: "updated succesfully!"
  else
    flash[:error]
    render :edit
  end  
end

def destroy
  if @question.destroy
    redirect_to questions_path
  else
    redirect_to questions_path, error: "We had trouble deleting your question"

  end
end

private

def find_question
  @question = current_user.questions.find(params[:id])

end

def question_params
  params.require(:question).permit([:title, :description, {category_ids: []}, :image])
end

####NOTE:  Code below commented out to test RSpec

 # #added when users added to confirm session first
 # before_action :authenticate_user!, except: [:index, :show]

 #  before_action :find_question, 
 #                only: [:edit, :destroy, :update,
 #                        :vote_up, :vote_down]  
 #                        #note that :show was removed from before_action due to change in find_question

  
 #  # SAME AS ABOVE
 #  # before_action :find_question, except: [:index, :show, :edit, :destroy, :update]



 #  def index
 #    @questions = Question.all
 #  end

 #  def new
 #    #instantiate a question variable
 #    @question = Question.new
 #  end 

 #  def show
 #    @question = Question.find(params[:question_id] || params[:id])
 #    @answer = Answer.new
 #    #NOTE HIGH number of instance variables above(convention is 2 per method)
 #    #this means we should refactor soon
 #    @answers = @question.answers.ordered_by_creation
 #    #Note that @answers is being used by show.html.haml to render data, which is then used to identify
 #    #partial page _answer.html.haml
 #    #NEEDS FIXING: @vote = current_user.vote_for(@question) || Vote.new
 #    @favourite = current_user.favourite_for(@question)
 #  end



 #  def update
 #    # @question = Question.find params[:id] -- REPLACED BY before_as action
 #    if @question.update_attributes(question_attributes)
 #    ##question_attributes protects from false updates
 #      redirect_to @question, notice: "Question updated successfully"
 #    else
 #      flash.now[:error] = "Unable to update"
 #      render :new
 #    end
 #  end 

 #  def destroy
 #    if  @question.destroy
 #    redirect_to questions_path, notice: "Question deleted successfully"
 #    else redirect_to questions_path, error: "We had trouble deleting your question"
 #    end
 #  end


 #  def create
 #    # COMMENTED OUT
 #    # question_attributes = params.require(:question).permit([:title, :description])
 #    @question = Question.new(question_attributes)

 #    ### @question = Question.new(params[:question])
 #    ### ^^forbidden in Rails 4+ for security reasons

 #      # same as below ^^
 #      # @question.title = params[:question][:title]
 #      # @question.title = params[:question][:description]

 #    ####for a user creating a question
 #    @question.user = current_user
 #    #Above replaces (do not use):
 #    #@question.user = current_user.questions.new(question_attributes)
 #    ####
 #     if  @question.save
 #      flash[:notice] = "Your question was created successfully!"
 #      redirect_to questions_path
 #    else
 #      flash.now[:error] = "Please correct the form"
 #      render :new
 #    end

 #  end

 #  def edit
 #    # @question = Question.find params[:id]

 #    # render text: "Editing #{params[:id]}"
 #  end


 #  # def vote_up
 #  #   @question.increment!(:vote_count) ##Increases vote count of question +1
 #  #   session[:has_voted] = true  ##Prevents multiple voting from user
 #  #   redirect_to @question
 #  # end

 #  # def vote_down
 #  # end

 #  def search
 #  end


 #  private 

 #  def find_question
 #    # @question = current_user.questions.find(params[:question_id] || params[:id])
 #    @question = current_user.questions.find_by_id(params[:id])
 #    redirect_to root_path, alert: "Access Denied" unless @question

 #    #This replaced by ^^ @question = Question.find(params[:question_id] || params[:id])
 #    ####This replaced by ^^ above:@question = Question.find params[:id]  Replaced with above^^

 #  end

 #  ##Method to define what's needed to create a new question
 #  def question_attributes
 #    question_attributes = params.require(:question).permit([:title, :description, {:category_ids => []}])
 #  end 

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
- if @question.errors.any?
  %ul
    - @question.errors.full_messages.each do |message|
      %li message


= simple_form_for @question, html: {class: "form-horizontal"}  do |f|
  = f.input :title, label: "question title"
  = f.input :description, label: "questions description"
  = f.collection_check_boxes :category_ids, Category.order("name"), :id, :name, item_wrapper_class: "form-group"
  /= f.collection_check_boxes :category_ids, Category.order("title"), :id, :title
  = f.input :image
  = f.submit class: "btn btn-default"


//////Replaced with an even simpler form above!
/ - if @question.errors.any?
/   %ul
/     - @question.errors.full_messages.each do |message|
/       %li message

/ = simple_form_for @question, html: {class: "form-horizontal"}  do |f|
/   = f.input :title, label: "question title", input_html: {class: "form-control"}
/   = f.input :description, label: "questions description", input_html: {class: "form-control"}
/   = f.collection_check_boxes :category_ids, Category.order("title"), :id, :title
/   %br
/   = f.submit class: "btn btn-default"


/////Simple form replaces all the following:

/ #- if @question.errors.any?
/   %ul
/     - @questions.errors.full_messages.each do |message|
/       %li= message
/ #= form_for @question do |f|
/   #= f.label :title, "question title"
/   #= f.text_field :title
/   %br/
/   #= f.label :description, "question description"
/   #= f.text_area :description
/   %br/
/   =# f.collection_check_boxes :category_ids, Category.order("name"), :id, :name

/   #= hidden_field_tag "question[category_ids][]", nil
/   - Category.order("name").each do |cat|
/     = check_box_tag "question[category_ids][]", cat.id, @question.category_ids.include?(cat.id), id: dom_id(cat)
/     #= label_tag dom_id(cat), cat.name
/     / # NOTE:  putting [category_ids][] with another "[]" enables data to be sent back as an array of multiple items
/     / # NOTE 2:  dom_id(cat) is a helper method for retrieving model_id, e.g. user_13
/     %br/
/   #= f.submit button_label, class: "btn btn-default"

/ /# %ul.listing
/ /#   - 10.times do |x|
/ /#    %li= link_to "Create New Question", new_question_path
/ /#    %h2= "x"

/ / 
/ / #= f.submit "Save", class: "btn btn-primary"
  
/ / # SAME AS ABOVE f.submit (@question.persisted? ? "Update" : "Save"), class: "btn btn-primary"

app/views/questions/create.html.haml
%h1 Creating Saved Question.....

app/views/questions/edit.html.haml
%h1 Editing question
= render "form", button_label: "Update question"
/-# NOTE Question to ask:  is it "form" or "_form" ?

app/views/questions/index.html.haml
%h1.title Listing Questions
= link_to "Create New Question", new_question_path

%h2 Recent Questions (cached)

//Cache of questions:
- cache "recent_questions", skip_digest: true do
  - @recent_questions.each do |question|
    = cache ["recent", question] do
      %div{id: "recent_#{dom_id(question)}"}
        %h2= link_to question.title, question
        %p.description= question.description
        %p
          Create On: #{formatted_date(question.created_at)}
        %hr


%h2 All Questions
- @questions.each do |question|
  = cache question do

    %div{id: dom_id(question)}
      %h2= link_to question.title, question_path(question)
      %p.description= question.description
      %p
        Created On: #{formatted_date(question.created_at)}
    /Note that *Formatted_date* REPLACED:
    / = question.created_at.strftime("%Y-%b-%d")
    
%hr/



/# Below code is jquery to increase %h1 font-size by 1px
/# parseInt() converts "20 px" into integer "20"
/# 
:javascript
  $("h1").each(function(){
    var fontSize = parseInt($(this).css("font-size"));
    fontSize++;
    $(this).css("font-size", fontSize + "px");
  });


//Practice Javascript:
//Below jQuery code adds UL/LI tags based on a number input
%h3.title "Listing all numbers:"

:javascript

  function generateUl(number) {
    
    var $ul = $("<ul></ul>");
    for(var i = 0; i < number; i++) {
      var $li = $("<li></li>", {text: "Element" + i});
      $ul.append($li);
    }
    $("body").append($ul);
  }
  generateUl(7);


//Below code prints all questions containing "abc"
:javascript

  $("h2:contains('Abc')").each(function(){

    // console.log($(this).text().length));
    x = $(this).text().length;
    $("body").append(x)

  });

//Writing a code that capitalizes all the text inside "h2" elements containing the letter "a"

:javascript

  $("h2:contains('A')").each(function(){

    console.log($(this).text().toUpperCase());

  });

//Writing a code that Upper Cases all the text inside "<a>" elements inside "h2" elements 
:javascript
  $("h2 a").each(function(){

    $(this).text( $(this).text().toUpperCase() );
  
  });

//Writing a code that capitalized all the text inside "a" elements inside "h2" elements

/ $("h2 a").each(function(){
/   var capitalizedText = $(this).text().charAt(0).toUpperCase() + $(this).text().slice(1);
/   $(this).text(capitalizedText);

/ });

//Writing a code that removes from the DOM a random H2 element

:javascript
  var randomnumber=Math.floor(Math.random() + $("h2").length())

  var $h2 = $("h2");
    $("h2").each(function(){
    Math.random()

    $h2.remove;

  });


:javascript

  function removeH2() {

    var index = Math.floor(Math.random() + $("h2").length);
    if($("h2").length > 0) {
      $("h2")[index].remove();
    }

  };

app/views/questions/new.html.haml
-#/ ##NOTE element from HERE transferred to _form.html.erb
%h1 Give me a question
= render "form" , button_label: "Save New Question"

app/views/questions/show.html.haml
%h1= @question.title
%p= @question.description
%p= formatted_date(@question.created_at)
/ ^^ NOTE formatted_date is an applicatiion helper method
/ %p= @question.created_at.strftime("%Y-%b-%d")
/ WHICH REPLACED THIS ^^ LINE

/Added for use with paperclip/upload gem
- if @question.image.present?
  /when imagemagick works we can reize:
  /#= image_tag @question.image.url(:medium)
  = image_tag @question.image.url

%p
- if @favourite
  = button_to "Unfavourite", question_favourite_path(@question, @favourite), method: :delete, class: "btn btn-danger"
- else
  %p= button_to "Favourite", question_favourites_path(@question), method: :post, class: "btn btn-info"

- if @question.favourited_users.present?
  Favourited Users:
  = @question.favourited_users.map(&:full_name).join(" , ")

%br
%hr


///Shows Categories of Question:
- if @question.categories.any?
  Categories (#{@question.categories.count}):
  = @question.categories.map(&:name).join(" ")
%br

/////New vote count system
%p

  / - if @vote.persisted? && @vote.is_up?
  /   = button_to "Undo", [@question, @vote], method: :delete, class: "btn btn-primary"

  / - else
  /   = form_for [@question, @vote] do |f|
  /     = f.hidden_field :is_up, value: true
  /     = f.submit "Vote Up", class: "btn btn-primary"
  / %br
  / = form_for [@question, @vote] do |f|
  /   = f.hidden_field :is_up, value: false
  /   = f.submit "Vote Down", class: "btn btn-primary"


////////////////////Old vote count system
/ Vote Count: #{@question.vote_count}

/ = @question.vote_count
/ %br/
/ - if session[:has_voted]
/   You voted already!
/ - else
/   = button_to "Vote Up", vote_up_question_path(@question)
/ %br/
///////////////////////

//CanCan User auth: "can?"
- if can? :edit, @question
  = link_to "Edit", edit_question_path(@question)
%br/
- if can? :destroy, @question
  = button_to "Delete", @question, method: :delete, data: {confirm: "Are you sure you want to delete this question?"}
%br/
= link_to "All Questions", questions_path


= render "answers/form"
//Renders the below from a partial:



.answers= render @answers
/Above allows each render to be contained within the div class ".answers"
/# = render @answers

/-# ^^If rendering PARTIAL, above is even MORE Succinct than:
/-# @answers.each do |answer|
/-#  = render "/answers/answer", answer: answer


/ -#  /Which REPLACED NEED TO POST THE CODE BELOW HERE.  The below code is now found at _answer.html.haml
/     -# @question.answers.each do |answer|

-#  / .well
-#  /   .col-sm-8.col-md.8.col-xs-8
-#  /     %p= answer.body
-#  /     %p Created on #{formatted_date(answer.created_at)}
-#  /   .col-sm-8.col-md.8.col-xs-8
-#  /     .pull-right= button_to "Delete", question_answer_path(@question, answer), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete this answer?"}