config/routes.rb
Weblog::Application.routes.draw do

  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, 
            controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

 get "/jspractices" => "jspractice#index"
 get "/exercise1" => "jspractice#exercise1"

  get "/about_us" => "home#about"

  get "/welcome" => "home#welcome"

  get "/faq" => "home#faq"

  get "/help" => "help#index"

    resources :answers, only: [] do
      resources :comments, only: [:create, :destroy]
    end

  resources :questions  do#, except: #OR# only: [:index, :new, :create]
    resources :favourites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
    
    resources :answers
     
     member do
        post :vote_up
        post :vote_down
      end
      
      post :search, on: :collection

    end

  root "questions#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
##Answer class was created in console with command line statement:
## ~> rails g model answer body:text question:references

has_many :comments, dependent: :destroy
belongs_to :user
#Links Comments model DB to Answer

validates_presence_of :body, message: "answer must contain text"

scope :ordered_by_creation, -> {order("created_at DESC")}
##Creates method :ordered_by_creation
#this method orders answers by the date created_at; DESC means Descending order

before_save :capitalize

def capitalize
  self.body = self.body.capitalize!
end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
##Class Answers Controller was generated separately after Answer Model was generated

before_action :find_question

def create
 
  @answer  = @question.answers.new(answer_attributes)
  @answer.user = current_user
  #Above ^^^ replaces below due to creation of User accounts
  # @question = Question.find params[:question_id]
  # @answer = Answer.new(answer_attributes)
  #answer_attributes is a private method taking care of NEW parameters
  
  respond_to do |format| ##Used for AJAX
    if @answer.save
      # AnswerMailer.notify_question_owner(@answer).deliver
      AnswerMailer.delay.notify_question_owner(@answer) #Note: Uses a Delay gem
      #format.html {redirect_to @question, notice: "Answer Submitted Successfully"} 
      format.html {redirect_to @question} #<-- if js not loaded 
      format.js {render} #<-- AJAX

    else
      format.html { render "/questions/show" } #if js not loaded
      format.js {render js: "alert('ERROR');"} ##AJAX added
    end
  end
end


def destroy
  #find_question replaced need for:  @question = Question.find(params[:question_id])
  @answer = @question.answers.find(params[:id])
  
  respond_to do |format| #Needed for Ajax

    ##Checks eligibility of current user
    if @answer.user == current_user && @answer.destroy
      #Before AJAX:  redirect_to @question, notice: "Answer deleted"
      format.html {}
      format.js{render}
    else
      #Before AJAX: redirect_to @question, alert: "We had trouble deleting the answer"
      format.html {}
      format.js {render}
    end
  end 
end

private

  ##private method to use for Answer.new
def answer_attributes
    params.require(:answer).permit([:body])
  end
 
# find_question was not needed in Answers Controller when Questions Controller.find_question added params[:question_id]
# UPDATE: Now adding find_question back now due to scoping for user permissions
def find_question
    @question = Question.find params[:question_id]
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.haml
/ Note this page is a partial.  We know this page is defined as a partial for Rails due to its underscore in the title:  _answer.html.haml

//NOTE: addition of {id: dom_id()} is for AJAX JS to reference
.well{id: dom_id(answer)}
  .row
    .col-sm-8.col-md.8.col-xs-8
      %p= answer.body
      %p Created on #{formatted_date(answer.created_at)}
    .col-sm-8.col-md.8.col-xs-8
      .pull-right= button_to "Delete", question_answer_path(@question, answer), method: :delete, class: "btn btn-danger", remote: true, class: "btn btn-danger"
      // remote:true needed for AJAX
      / = link_to "Test Me" Javascript 

app/views/answers/_form.html.haml
%h2 Add An Answer
- if @answer.errors.any?
  %ul
    - @answer.errors.full_messages.each do |message|
      %li= message

/=# form_for [@question, @answer] do |f|
/=#INSERT AJAX HERE

= form_for [@question, @answer], remote: true do |f|
  = f.text_area :body
  
  /# Note "data: {disable_with: "saving"} is used user interface when waiting for a server to save
  = f.submit "Submit an answer", class: "btn btn-primary", data: {disable_with: "Saving..."}

/ OLD Form before AJAX was used:
/ =# form_for @answer, url: question_answers_path(@question) do |f|
/   =# f.text_area :body
/   %br
/   =# f.submit "Submit an answer", class: "btn btn-primary"
/ %hr

/-# @question.answers.each do |answer|
/#   .well
/#   .row
/#     .col-smm-8.col-md-8.col-xs-8
/#       %p= answer.body
/#       %p Created on: #{formatted_date(answer.created_at)}
/#     .col-smm-8.col-md-8.col-xs-8
/#       .pull-right= button_to "Delete", question_answers_path(@question,@answer), method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete the answer?"}
/ %hr

app/views/answers/create.js.haml
/ $("#answer_body").html("#{j rendewr 'form'}");
/ $("#answer_body").val("");

//Appends typed in answers to the top of @answer
//$(".answers").prepend("#{@answer.body}")

//Renders the _answer partial via AJax
$(".answers").prepend("#{j render 'answer', answer: @answer}")

/ #("##{dom_id(@answer)}").hide().fadeIn(1000)");


//Makes AJAX add of answer fade in
/ $("##{dom_id(@answer)}").hide().fadeIn(500)

//Error message
$(".answeradd").prepend("#{@answer.body}")

app/views/answers/destroy.js.haml
/ $(".answers").prepend("#{j render 'answer', answer: @answer}")


//Makes AJAX add of answer fade out upon delete
//Remember:  AJAX will not work if JS is nested in HAML.

$("##{dom_id(@answer)}").fadeOut(600, function(){$(this).remove();});