config/routes.rb
Weblog::Application.routes.draw do

  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, 
            controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

 get "/jspractices" => "jspractice#index"
 get "/exercise1" => "jspractice#exercise1"

  get "/about_us" => "home#about"

  get "/welcome" => "home#welcome"

  get "/faq" => "home#faq"

  get "/help" => "help#index"

    resources :answers, only: [] do
      resources :comments, only: [:create, :destroy]
    end

  resources :questions  do#, except: #OR# only: [:index, :new, :create]
    resources :favourites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]
    
    resources :answers
     
     member do
        post :vote_up
        post :vote_down
      end
      
      post :search, on: :collection

    end

  root "questions#index"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
  %title Weblog
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
  %body
  .container
    %nav.navbar.navbar-default{role: "navigation"}
      = link_to "Home", welcome_path
      = link_to "JSPractice", jspractices_path
      = link_to "Questions Index", root_path
      = link_to "About Us", about_us_path, class: "btn-primary", id: "about", style: "float: left;"
      .pull-right
        - if user_signed_in?
          hello
          = button_to "sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary"
        - else
          = link_to "sign in", new_user_session_path, class: "btn btn-primary"
          = link_to "Sign in w/ Twitter", user_omniauth_authorize_path(:twitter)

    - if flash[:notice] 
      .alert.alert-success= flash[:notice]
    - elsif flash[:error]
      .alert.alert-danger= flash[:error]
  = yield